workflows:
  ios-simulator:
    name: iOS Simulator Build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build for iOS Simulator
        script: flutter build ios --simulator
    artifacts:
      - build/ios/iphonesimulator/**/*.app