// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgDFB7qwdGBOgslUwzKzRYEEKHDgcnz4M',
    appId: '1:62881174597:web:0317a364238c2b156dff2c',
    messagingSenderId: '62881174597',
    projectId: 'testzawag',
    authDomain: 'testzawag.firebaseapp.com',
    storageBucket: 'testzawag.firebasestorage.app',
    measurementId: 'G-YRQVBQYYC3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPjP_2XpDOlr8FI06qiBhHdYQrQHmbuJA',
    appId: '1:62881174597:android:35df30b7dc6e29fc6dff2c',
    messagingSenderId: '62881174597',
    projectId: 'testzawag',
    storageBucket: 'testzawag.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmt9UikhNYM00Im7ZTh3kTsRB1KTJ8xms',
    appId: '1:62881174597:ios:9f2349e0fc09d07a6dff2c',
    messagingSenderId: '62881174597',
    projectId: 'testzawag',
    storageBucket: 'testzawag.firebasestorage.app',
    iosBundleId: 'com.example.aiHelper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmt9UikhNYM00Im7ZTh3kTsRB1KTJ8xms',
    appId: '1:62881174597:ios:9f2349e0fc09d07a6dff2c',
    messagingSenderId: '62881174597',
    projectId: 'testzawag',
    storageBucket: 'testzawag.firebasestorage.app',
    iosBundleId: 'com.example.aiHelper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgDFB7qwdGBOgslUwzKzRYEEKHDgcnz4M',
    appId: '1:62881174597:web:21a1af70f5b666986dff2c',
    messagingSenderId: '62881174597',
    projectId: 'testzawag',
    authDomain: 'testzawag.firebaseapp.com',
    storageBucket: 'testzawag.firebasestorage.app',
    measurementId: 'G-2Y4Y2BHGDE',
  );
}
